Fix the Hugo command by providing a tmp dir
If not provided, Hugo fails with the following error message:

Error: add site dependencies: create deps: failed to create file caches
from configuration: mkdir /tmp/hugo_cache/modules: permission denied

Therefore the environment variable is set before the execution.