Update the Hugo guide (#461)
* Update Hugo version and add some fixes

* Fix the Hugo command by providing a tmp dir

If not provided, Hugo fails with the following error message:

Error: add site dependencies: create deps: failed to create file caches
from configuration: mkdir /tmp/hugo_cache/modules: permission denied

Therefore the environment variable is set before the execution.

* Update guide_hugo.rst